version: "3.7"
services:
    letsencrypt:
        image: linuxserver/letsencrypt
        container_name: letsencrypt
        cap_add:
          - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Riga
            - URL=eizvertins.com
            - SUBDOMAINS=cloud
            - VALIDATION=http 
            - EMAIL=eizvertins.edgars@gmail.com
        volumes:
          - /home/pi/docker-volumes/letsencrypt/config:/config
        ports:
          - 443:443
          - 80:80
        restart: unless-stopped
    nextcloud:
        image: linuxserver/nextcloud
        container_name: nextcloud
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Riga
        volumes:
            - /home/pi/docker-volumes/ncdata:/config
            - /mnt/toshiba750/ncdata:/data
        ports:
            - 1500:443
        restart: unless-stopped
    rpi-monitor:
        image: michaelmiklis/rpi-monitor
        container_name: rpi-monitor
        devices:
            - /dev/vchiq:/dev/vchiq 
            - /dev/vcsm:/dev/vcsm
        volumes:
            - /home/pi/docker-volumes/rpi-monitor/opt/vc:/opt/vc 
            - /home/pi/docker-volumes/rpi-monitor/boot:/boot 
            - /home/pi/docker-volumes/rpi-monitor/sys:/dockerhost/sys:ro 
            - /home/pi/docker-volumes/rpi-monitor/etc:/dockerhost/etc:ro 
            - /home/pi/docker-volumes/rpi-monitor/proc:/dockerhost/proc:ro 
            - /home/pi/docker-volumes/rpi-monitor/usr/lib:/dockerhost/usr/lib:ro 			
        ports:
            - 8888:8888
        restart: unless-stopped
    
