version: "3.7"
services:
    nginx-proxy-manager:
        image: jlesage/nginx-proxy-manager
        container_name: nginx-proxy
        ports:
        - 8181:8181
        - 8080:8080
        - 4443:4443
        volumes:
        - /home/pi/docker-volumes/nginx-proxy-manager:/config:rw
    nextcloud:
        image: linuxserver/nextcloud
        container_name: nextcloud
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Riga
        volumes:
            - /home/pi/docker-volumes/ncdata:/config
            - /mnt/toshiba750/ncdata:/data
        ports:
            - 1500:443
        restart: unless-stopped
    
