version: "3.7"
services:
    nginx-proxy-manager:
        image: jc21/nginx-proxy-manager:latest
        container_name: nginx-proxy-manager
        restart: unless-stopped
        ports:
            - 80:80
            - 81:81
            - 443:443
        volumes:
            - /home/pi/docker-volumes/nginx-proxy-manager/config:/app/config/production.json
            - /home/pi/docker-volumes/nginx-proxy-manager/data:/data
            - /home/pi/docker-volumes/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
        depends_on:
            - nginx-proxy-db
        environment:
            - FORCE_COLOR=1
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Riga
    nginx-proxy-db:
        image: linuxserver/mariadb
        container_name: nginx-proxy-db
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Riga
            - MYSQL_ROOT_PASSWORD=dbMpass101mM            
            - MYSQL_DATABASE=nginxproxy
            - MYSQL_USER=user
            - MYSQL_PASSWORD=dbMpass101mM
        volumes:
          - /home/pi/docker-volumes/nginx-proxy-db/config:/config
        ports:
            - 3306:3306
        restart: unless-stopped
    nextcloud:
        image: linuxserver/nextcloud
        container_name: nextcloud
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Riga
        volumes:
            - /home/pi/docker-volumes/ncdata:/config
            - /mnt/toshiba750/ncdata:/data
        ports:
            - 1500:443
        restart: unless-stopped
    
