version: "3.7"
services:
    letsencrypt:
        image: linuxserver/letsencrypt
        container_name: letsencrypt
        cap_add:
          - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Riga
            - URL=eizvertins.com
            - SUBDOMAINS=cloud
            - VALIDATION=http 
            - EMAIL=eizvertins.edgars@gmail.com
        volumes:
          - /home/pi/docker-volumes/letsencrypt/config:/config
        ports:
          - 443:443
          - 80:80
        restart: unless-stopped
    nextcloud:
        image: linuxserver/nextcloud
        container_name: nextcloud
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Riga
        volumes:
            - /home/pi/docker-volumes/ncdata:/config
            - /mnt/toshiba750/ncdata:/data
        ports:
            - 1500:443
        restart: unless-stopped
    
