version: "3.7"
services:
    nginx-proxy-manager:
        image: jc21/nginx-proxy-manager:latest
        container_name: nginx-proxy        
        restart: always
        ports:
            - 80:80
            - 81:81
            - 443:443
        volumes:
            - /home/pi/docker-volumes/nginx-proxy-manager/config.json:/app/config/production.json
            - /home/pi/docker-volumes/nginx-proxy-manager/data:/data
            - /home/pi/docker-volumes/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
        depends_on:
            - nginx-proxy-db
        environment:
        # if you want pretty colors in your docker logs:
            - FORCE_COLOR=1
    nginx-proxy-db:
        image: mariadb:latest
        container_name: nginx-proxy-db
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: "npmRootPass101"
          MYSQL_DATABASE: "npm"
          MYSQL_USER: "npm"
          MYSQL_PASSWORD: "npmRootPass101"
        volumes:
          - /home/pi/docker-volumes/nginx-proxy-db/data/mysql:/var/lib/mysql
    nextcloud:
        image: linuxserver/nextcloud
        container_name: nextcloud
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Riga
        volumes:
            - /home/pi/docker-volumes/ncdata:/config
            - /mnt/toshiba750/ncdata:/data
        ports:
            - 1500:443
        restart: unless-stopped
    
