version: "3.7"
services:
    letsencrypt:
        image: linuxserver/letsencrypt
        container_name: letsencrypt
        cap_add:
          - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Riga
            - URL=eizvertins.com
            - SUBDOMAINS=cloud,monitor
            - VALIDATION=http 
            - EMAIL=eizvertins.edgars@gmail.com
        volumes:
          - /home/pi/docker-volumes/letsencrypt/config:/config
        ports:
          - 443:443
          - 80:80
        restart: unless-stopped
    nextcloud:
        image: linuxserver/nextcloud
        container_name: nextcloud
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Riga
        volumes:
            - /home/pi/docker-volumes/ncdata:/config
            - /mnt/toshiba750/ncdata:/data
        ports:
            - 1500:443
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '3.00'
    rpi-monitor:
        image: michaelmiklis/rpi-monitor
        container_name: rpi-monitor
        devices:
            - /dev/vchiq:/dev/vchiq 
            - /dev/vcsm:/dev/vcsm
        volumes:
            - /opt/vc:/opt/vc
            - /boot:/boot
            - /sys:/dockerhost/sys:ro
            - /etc:/dockerhost/etc:ro
            - /proc:/dockerhost/proc:ro
            - /usr/lib:/dockerhost/usr/lib:ro
        ports:
            - 8888:8888
        restart: unless-stopped
    ghost-edgars:
        image: ghost
        container_name: ghost-edgars
        restart: unless-stopped
        ports:
            - 3001:2368
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Riga
        volumes:
            - /home/pi/docker-volumes/ghost/edgars:/var/lib/ghost/content